kind: Namespace
apiVersion: v1
metadata:
  name: foo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: foo-v2
  namespace: foo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foo
      version: v2
  template:
    metadata:
      labels:
        app: foo
        version: v2
    spec:
      containers:
      - name: whereami
        image: gcr.io/google-samples/whereami:v1.2.1
        ports:
          - containerPort: 8080
        env:
        - name: METADATA
          value: "foo-v2"
---
apiVersion: v1
kind: Service
metadata:
  name: foo-v2
  namespace: foo
spec:
  selector:
    app: foo
    version: v2
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: foo-v2
  namespace: foo